### ISSUE TITLE
Primary tasks should be scrollable

### ISSUE THREAD

**Issue by M3L6H** [M3L6H/Bloom#93]
In the interest of minimalism, we made primary tasks only show the top three tasks, but that's actually more of a burden than a feature. Let's show all the tasks on the home page, but make it scrollable.

Additionally, when a user completes a task, instead of removing it from the list, it should be moved to the bottom of the list.

**Comment by ashehwang** [comment]
I feel that'd be an overlap between the main show page vs tasks (drag and drop) page. How about if we add a little line explaining these are your top three priorities for now? It just needs to be more clear.
